#!/bin/sh

# TODO: script to generate function pointer array stuff

analyzer_args="-fanalyzer "
sanitizer_args="-fsanitize=address,undefined "
output_file="main"
tests_file="tests.c"

gcc_command()
{
    gcc -std=c11 -Wall -Wextra -Wformat-overflow -Wuse-after-free=1 \
        -Wstrict-prototypes -Wconversion -Wno-override-init \
        -Werror -fmax-errors=1 -O0 -g3 \
        ${1} -o "${output_file}" "${tests_file}" rwlj.h
}

gcc_command "${analyzer_args}" -o main rwlj.h tests.c && gcc_command "${sanitizer_args}" -o main rwlj.h tests.c && ./main
