#!/usr/bin/env python

# Generate array of pointers to test procedures

import re
import sys

TEST_FILE: str = "tests.c"
BACKUP_FILE: str = f"{TEST_FILE}.bkp"

text: list[str] = []
procs: list[str] = []
test_procs_arr_idxs: list[int] = []
with open(TEST_FILE, "r+") as file:
    text = list(file)
    for i in range(len(text)):
        if re.match(r"void", text[i]):
            match = re.match(r"(test_\w+)\(void\)", text[i + 1])
            if match:
                procs.append(match[1])
        elif re.match(r"rwljTest_Proc.*\[\].*{", text[i]):  # }
            test_procs_arr_idxs.append(i + 1)
        elif len(test_procs_arr_idxs) == 1 and re.match(r"};", text[i]):
            test_procs_arr_idxs.append(i)
            break

    if len(procs) <= 0:
        print(
            "No procedures of signature 'void proc(void)' were found", file=sys.stderr
        )
        exit(1)
    elif len(test_procs_arr_idxs) <= 1:
        print("rwljTest_Proc array not found", file=sys.stderr)
        exit(2)

    first_idx, last_idx = test_procs_arr_idxs[0], test_procs_arr_idxs[1]
    procs_in_test_arr = text[first_idx:last_idx]

    test_arr_has_changed = False
    if len(procs) == len(procs_in_test_arr):
        idx = first_idx
        for proc in procs:
            if not re.search(rf"{proc}", text[idx]):
                test_arr_has_changed = True
                break
            idx += 1
    else:
        test_arr_has_changed = True

    # No procedure definitions were changed
    if not test_arr_has_changed:
        exit(0)

    with open(BACKUP_FILE, "w") as backup:
        backup.write("".join(text))

    for _ in range(last_idx - first_idx):
        text.pop(first_idx)

    procs.reverse()
    for proc in procs:
        indentation = " " * 4
        text.insert(first_idx, f"{indentation}{proc},\n")

with open(TEST_FILE, "w") as file:
    file.write("".join(text))
